version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: .docker/jekyll.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    working_dir: /app
    command: "jekyll serve --host=0.0.0.0 --force_polling"
