### Instalar plugin REST en VSCode (Ejemplo PUT Productos)
@token=YOUR_TOKEN_HERE
@firma=YOUR_SIGNATURE_HERE
@fecha=DATETIME_YYYY-MM-DDTHH:MM:SS
@server=http://sandbox.marketsync.mx/api/
PUT {{server}}productos?timestamp={{fecha}}&token={{token}}&version=1.0&signature={{firma}}

# Body
[
    {
      "product_id": 279852,
      "nombre": "Product Test update name"
    }
]

